[project]
name = "gen-ai-code"
version = "0.1.0"
description = ""
authors = [
    {name = "Rolandas",email = "rzabulis@yahoo.co.uk"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai (>=1.65.3,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
